version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/duckduckgoose
    environment:
      DATABASE_URL: sqlite:///data/duckduckgoose.sqlite
      MIX_ENV: dev
  db:
    image: alpine:3.17  # Lightweight image for sqlite3
