apiVersion: v1
kind: Service
metadata:
  name: duckduckgoose-service
spec:
  selector:
    app: duckduckgoose-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer